### ISSUE TITLE
Мелкие правки

### ISSUE THREAD

**Issue by ivan-podgornov** [vasilich99/dreams#8]
- [x] Удалить next.config.js
- [x] Использовать background-image, а не [background](https://github.com/vasilich99/dreams/blob/1be4d90deceff6c4c271a17686c6cc2db79865bb/src/assets/styles.css#L9).
- [x] [categories](https://github.com/vasilich99/dreams/blob/1be4d90deceff6c4c271a17686c6cc2db79865bb/src/components/dream-categories/dream-categories.jsx#L6) лучше вынести в отдельный файл categories.js
- [x] В DreamReview для стейта dream по умолчанию устанавливается объект с "пустой" мечтой. Лучше изначальным значением сделать null и добавить стейт loading. А если ещё как-то показывать, что мечта загружается пока она загружается, будет очень круто.
- [x] DreamReview [загружает](https://github.com/vasilich99/dreams/blob/1be4d90deceff6c4c271a17686c6cc2db79865bb/src/components/dream-review/dream-review.jsx#L28) весь список dreams и потом ищет нужную по id. Можно сразу загрузить нужную по id.
- [x] Убрать упоминание о [localhost](https://github.com/vasilich99/dreams/blob/1be4d90deceff6c4c271a17686c6cc2db79865bb/src/components/dream-review/dream-review.jsx#L103). Название домена можно взять с роутера или если там такого нет, с document.location
- [x] В Dreams-list если не найдено ни одной мечты, пишет "Загрузочка". Лучше добавить стейт loading, который равен true пока мечты загружаются и опираться на него.
- [x] Для ссылок, где есть [onKeyDown](https://github.com/vasilich99/dreams/blob/7d9f401997d0b9999440bcb5c0976d496112156c/src/components/dreams-list/dreams-list.jsx#L58) нужно сделать, чтобы обработчик не на каждую клавишу срабатывал, а только на Enter и пробел

**Comment by vasilich99** [comment]
- DreamReview загружает весь список dreams и потом ищет нужную по id. Можно сразу загрузить нужную по id.
Это сам dreams.js, который в api находится, редачить нужно?

**Comment by ivan-podgornov** [comment]
Нужно посмотреть в firebase как по id загрузить что-то и использовать это. Да, в dreams.js нужно будет добавить метод getById. Типа того

**Comment by vasilich99** [comment]
ну и гамно, конечно. Вообще я не так думал)
